name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_REGION: ap-southeast-2
  STAGE: dev

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role
        aws-region: ${{ env.AWS_REGION }}

    - name: Build, tag, and push image to Amazon ECR
      run: bash docker/deploy.sh

    - name: Force ECS deployment
      run: |
        aws ecs update-service \
        --cluster laravel-${{ env.STAGE }}-ecs-cluster \
        --service laravel-${{ env.STAGE }}-ecs-service \
        --force-new-deployment
